examples/esm/app.vue
examples/esm/components/CopyPage.vue
examples/esm/components/MenuPage.vue
examples/esm/components/grid.vue
examples/esm/router.js
src/components/emfe-copy/index.js
src/components/emfe-copy/src/EmfeCopy.vue
src/components/emfe-menu/src/EmfeMenu.vue
src/contant.js
src/index.js
src/styles/config.scss
src/styles/emfe-menu/emfe-menu.scss
src/tools/o.js
src/tools/screen.js

1. copy component
2. Perfect navigation

feature:  copy component

---

README.md
examples/esm/app.vue
examples/esm/components/TooltipPage.vue
src/components/emfe-tooltip/src/EmfeTooltip.vue
src/index.js

1. edit tooltip api
2. perfect README
3. rename emui to emfe

feature: edit api and perfect README

---

examples/esm/app.vue
examples/esm/components/DatePage.vue
examples/esm/components/TimePage.vue
examples/esm/router.js
src/components/emfe-time/index.js
src/components/emfe-time/src/EmfeTime.vue
src/index.js
src/styles/emfe-time/emfe-time.scss
src/styles/emfe.scss
src/tools/time.js

1. time component
2. edit date api

feature: time component and edit date api

---

examples/esm/components/DragPage.vue

1. Drag and drop element hierarchy issues
2. Two conflicts between drag and drop elements

fix: drag demo

---

examples/esm/app.vue
examples/esm/components/DatetimePage.vue
examples/esm/router.js
src/components/emfe-date/src/EmfeDate.vue
src/components/emfe-datetime/index.js
src/components/emfe-datetime/src/EmfeDatetime.vue
src/components/emfe-time/src/EmfeTime.vue
src/index.js
src/styles/emfe-datetime/emfe-datetime.scss
src/styles/emfe.scss
src/tools/time.js

1. add datetime component
2. fix bug ---- Disable time cannot be selected automatically after selection time

feature: datetime cpt and fix time bugs

---

examples/esm/app.vue
examples/esm/components/TablePage.vue
examples/esm/router.js
src/components/emfe-table/index.js
src/components/emfe-table/src/EmfeTable.vue
src/components/emfe-table/src/EmfeTableBody.vue
src/components/emfe-table/src/EmfeTableHead.vue
src/index.js
src/styles/config.scss
src/styles/emfe-input/emfe-input.scss
src/styles/emfe-table/emfe-table.scss
src/styles/emfe.scss

feature:create  @emfe-table
@iq9891

feature:create emfe-table

---

examples/esm/app.vue
examples/esm/components/DropPage.vue
examples/esm/router.js
src/components/emfe-drag/src/EmfeDrag.vue
src/components/emfe-drop/index.js
src/components/emfe-drop/src/EmfeDrop.vue
src/index.js

feature:create emfe-drop @iq9891

feature:create emfe-drop

---

examples/esm/components/Inputpage.vue
examples/esm/components/TablePage.vue
src/components/emfe-input/src/EmfeInput.vue
src/components/emfe-table/src/EmfeTable.vue
src/index.js
src/styles/emfe-input/emfe-input.scss

fix:input API instructions
fix: index table component location corresponding

index table component location corresponding && input table API instructions

---

examples/esm/app.vue
examples/esm/components/Inputpage.vue
examples/esm/components/TagPage.vue
examples/esm/router.js
src/components/emfe-input/src/EmfeInput.vue
src/components/emfe-tag/index.js
src/components/emfe-tag/src/EmfeTag.vue
src/components/emfe-tag/src/EmfeTagParent.vue
src/index.js
src/styles/emfe-input/emfe-input.scss
src/styles/emfe-tag/emfe-tag.scss
src/styles/emfe.scss

feature : tag component and fix input className and fix color @iq9891 
--

	feature : tag component and fix input className and fix color

---

examples/esm/components/TablePage.vue
src/components/emfe-table/src/EmfeTable.vue
src/components/emfe-table/src/EmfeTableBody.vue
src/components/emfe-table/src/EmfeTableHead.vue
src/styles/emfe-input/emfe-input.scss
src/styles/emfe-panel/emfe-panel.scss
src/styles/emfe-table/emfe-table.scss
src/styles/emfe-tag/emfe-tag.scss

fix color variable and  fix: table className

fix color variable

---

examples/esm/components/ButtonPage.vue
src/components/emfe-button/src/EmfeButton.vue
src/styles/emfe-button/emfe-button.scss

1. button add click method
2. fix button text color in disabled

feature: button add click method

---

examples/esm/components/styles/TablePage.vue
examples/esm/components/styles/checkoutPage.vue
src/components/emfe-checkout/src/EmfeCheckout.vue
src/components/emfe-table/src/EmfeTableBody.vue
src/components/emfe-table/src/EmfeTableHead.vue
src/styles/emfe-table/emfe-table.scss

fix tabke and  checkout 

---

examples/esm/components/functions/SelectPage.vue
examples/esm/components/functions/modal.vue
examples/esm/components/styles/TablePage.vue
examples/esm/components/styles/TagPage.vue
src/components/emfe-modal/src/EmfeModal.vue
src/components/emfe-select/src/EmfeSelect.vue
src/components/emfe-table/src/EmfeTableBody.vue
src/components/emfe-tag/src/EmfeTag.vue
src/components/emfe-tag/src/EmfeTagParent.vue
src/styles/emfe-modal/emfe-modal.scss
src/styles/emfe-tag/emfe-tag.scss

fix table slot and tag remove list

fix table slot and tag remove list

---

examples/esm/components/styles/Panelpage.vue
src/components/emfe-panel/src/EmfePanel.vue

fix panelpage

---

examples/esm/components/styles/PaginationPage.vue
src/components/emfe-pagination/src/EmfePagination.vue

fix:page error

---

src/styles/emfe-pagination/emfe-pagination.scss

fix:yi chang

---

src/components/emfe-menu/src/EmfeMenu.vue

fix: goods add new open window

fix: goods add new open window

---

src/components/emfe-header/src/EmfeHeader.vue

fix: change text

---

examples/esm/components/functions/ColorPage.vue
src/components/emfe-color/src/EmfeColor.vue

fix($colorPick): modify colorPick

---

src/components/emfe-dialog/index.js
src/components/emfe-dialog/src/EmfeDialog.vue
src/index.js
src/styles/emfe-dialog/emfe-dialog.scss
src/styles/emfe.scss

feat($dialog): add dialog components

---

package.json
src/components/emfe-bar/src/EmfeBar.vue
src/styles/emfe-bar/emfe-bar.scss

fix($reload) reload bar url

---

src/components/emfe-bar/src/EmfeBar.vue
src/tools/constantenv.js
src/tools/development.js

fix($member) fix member project

fix($member) fix member project

---

src/components/emfe-bar/src/EmfeBar.vue
src/tools/constantenv.js
src/tools/development.js

fix($crm) fix crm url

---

src/components/emfe-bar/src/EmfeBar.vue

fix($HumanInput) fix HumanInput

fix($HumanInput) fix HumanInput

---

src/components/emfe-bar/src/EmfeBar.vue

fix($hotfix) hotfix-url

---

src/components/emfe-header-active/src/EmfeHeaderActive.vue

fix($headeractive page): fix headeractive page menu

---

examples/esm/components/functions/DatetimeMPage.vue
examples/esm/components/styles/Inputmorepage.vue
package.json
src/components/emfe-datetime-m/src/EmfeDatetimeM.vue
src/components/emfe-inputmore/src/EmfeInputmore.vue
src/components/emfe-inputmore/src/EmfeInputmoreGroup.vue
src/styles/emfe-inputmore/emfe-inputmore.scss

fix($emfe): fix inputmore

---

examples/esm/components/functions/SelectPage.vue
package.json
src/components/emfe-select/src/EmfeSelect.vue

fix($emfe): fix select component bug

fix($emfe): fix select component bug
